// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE0kmUHTV3EeTvuUXidrxYNSCAdJSnm5w',
    appId: '1:398835549126:web:514911de8e692960f068c7',
    messagingSenderId: '398835549126',
    projectId: 'mugen-eiyaku',
    authDomain: 'mugen-eiyaku.firebaseapp.com',
    storageBucket: 'mugen-eiyaku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1kV-Z-1UftZn2jNIQTdU8fFctKCJ9AA',
    appId: '1:398835549126:android:1dac11ad480b9a38f068c7',
    messagingSenderId: '398835549126',
    projectId: 'mugen-eiyaku',
    storageBucket: 'mugen-eiyaku.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9zKMxYxgs0O_4by6BnXuv173go4FfF0',
    appId: '1:398835549126:ios:064dc676f165ebb4f068c7',
    messagingSenderId: '398835549126',
    projectId: 'mugen-eiyaku',
    storageBucket: 'mugen-eiyaku.firebasestorage.app',
    iosClientId: '398835549126-n93t9i809o9lah70p997lp4th51gdl6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishLearningApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9zKMxYxgs0O_4by6BnXuv173go4FfF0',
    appId: '1:398835549126:ios:064dc676f165ebb4f068c7',
    messagingSenderId: '398835549126',
    projectId: 'mugen-eiyaku',
    storageBucket: 'mugen-eiyaku.firebasestorage.app',
    iosClientId: '398835549126-n93t9i809o9lah70p997lp4th51gdl6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE0kmUHTV3EeTvuUXidrxYNSCAdJSnm5w',
    appId: '1:398835549126:web:a28b122ae7619badf068c7',
    messagingSenderId: '398835549126',
    projectId: 'mugen-eiyaku',
    authDomain: 'mugen-eiyaku.firebaseapp.com',
    storageBucket: 'mugen-eiyaku.firebasestorage.app',
  );

}